spring.application.name=finan

server.port=8000

# secret usado para segurança do JWT
jwt.secret = "JWT_SECRET=bXlTdXBlclNlY3JldEtleUFxdWlFeGVtcGxvMTIzNDU2Nzg5MDEyMw=="

# 8 horas em milisegundos
jwt.token.expiration_in_millis=28800000
spring.profiles.active=${ACTIVE_PROFILE:dev}

# Configurações de e-mail
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.from=${MAIL_FROM:noreply@codegroup.com}